name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Enable pnpm
        run: corepack enable
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: TypeScript check
        run: pnpm typecheck || true
        continue-on-error: true
      
      - name: Lint check
        run: pnpm lint || true
        continue-on-error: true
      
      - name: Run unit tests
        run: pnpm test:unit
      
      - name: Build application
        run: pnpm build
      
      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium --with-deps
      
      - name: Run E2E tests
        run: pnpm test:e2e
        continue-on-error: true
      
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  lighthouse:
    name: Lighthouse CI
    needs: build_test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Enable pnpm
        run: corepack enable
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build application
        run: pnpm build
      
      - name: Run Lighthouse CI
        run: |
          pnpm dlx @lhci/cli@0.13.0 autorun \
            --collect.startServerCommand="pnpm start" \
            --collect.url="http://localhost:3000" \
            --collect.numberOfRuns=3
        continue-on-error: true
      
      - name: Upload Lighthouse results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 7

